### ISSUE TITLE
R unexpectedly quits after running glmm.wald?

### ISSUE THREAD

**Issue by jinshaw16** [hanchenphd/GMMAT#1]
Dear Han,

Sorry to disturb you with this, I am hopeful to use GMMAT on an analysis I am undertaking but am struggling to get the package to work. I installed the library via devtools install_git() and have put the outcome from the installation at the bottom of this message. I then load the package seemingly successfully, but once I try and run the glmm.wald command, R quits with the following error:

"
*** caught segfault ***
address 0x10, cause 'memory not mapped'

Traceback:
 1: .Call(C_glmm_wald_text, nn, snp, infile, tol, "c", miss.method,     infile.nrow, infile.nrow.skip, infile.sep, infile.na, infile.ncol.skip,     infile.ncol.print, snp.col, select)
 2: glmm.wald(fixed = pheno ~ Sex, data = p, infile = paste0(path,     "gmmat_", chromosome, "_", cohort, ".gz"), kins = GRM, family = binomial(link = "logit"),     snps = s)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
"

Is this something you have come across before? I have tried uninstalling and re installing all my R packages. I have installed the armadillo and boost libraries via anaconda3 and loaded the environment for which I have installed those libraries. I do have a suspicion that possibly the R installation of Rcpparmadillo may not be communicating with the anaconda version of the armadillo library, but I have set my LD_LIBRARY_PATH so that it should look in the anaconda locations first.

My sessionInfo() is:

"
R version 3.4.4 (2018-03-15)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4
"

My other suspicion is that there might be some compiling issues when installing the package? I have pasted the output from the installation process below. If you have any suggestions with regards to how I can get this working it would be much appreciated.

Many thanks in advance for any help you might be able to provide with this!

Best wishes,

Jamie

"
Downloading git repo https://github.com/hanchenphd/GMMAT.git
Installing GMMAT
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL '/tmp/RtmpdTY9EU/fileba264d9ca0c'  \
  --library='/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘GMMAT’ ...
** libs
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I"/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c fitglmm.cpp -o fitglmm.o
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:53:64: warning: declaration of ‘double dasum_(const int*, const double*, const int*)’ with C language linkage [enabled by default]
 F77_NAME(dasum)(const int *n, const double *dx, const int *incx);
                                                                ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:28:22: warning: conflicts with previous declaration ‘double arma::dasum_(arma::blas_int*, const double*, arma::blas_int*)’ [enabled by default]
   #define arma_dasum dasum
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:86:10: note: in expansion of macro ‘arma_fortran’
   double arma_fortran(arma_dasum)(blas_int* n, const double* x, blas_int* incx);
          ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:86:23: note: in expansion of macro ‘arma_dasum’
   double arma_fortran(arma_dasum)(blas_int* n, const double* x, blas_int* incx);
                       ^
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:63:42: warning: declaration of ‘double ddot_(const int*, const double*, const int*, const double*, const int*)’ with C language linkage [enabled by default]
         const double *dy, const int *incy);
                                          ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:34:22: warning: conflicts with previous declaration ‘double arma::ddot_(arma::blas_int*, const double*, arma::blas_int*, const double*, arma::blas_int*)’ [enabled by default]
   #define arma_ddot  ddot
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:92:10: note: in expansion of macro ‘arma_fortran’
   double arma_fortran(arma_ddot)(blas_int* n, const double* x, blas_int* incx, const double* y, blas_int* incy);
          ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:92:23: note: in expansion of macro ‘arma_ddot’
   double arma_fortran(arma_ddot)(blas_int* n, const double* x, blas_int* incx, const double* y, blas_int* incy);
                       ^
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:65:64: warning: declaration of ‘double dnrm2_(const int*, const double*, const int*)’ with C language linkage [enabled by default]
 F77_NAME(dnrm2)(const int *n, const double *dx, const int *incx);
                                                                ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:31:22: warning: conflicts with previous declaration ‘double arma::dnrm2_(arma::blas_int*, const double*, arma::blas_int*)’ [enabled by default]
   #define arma_dnrm2 dnrm2
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:89:10: note: in expansion of macro ‘arma_fortran’
   double arma_fortran(arma_dnrm2)(blas_int* n, const double* x, blas_int* incx);
          ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:89:23: note: in expansion of macro ‘arma_dnrm2’
   double arma_fortran(arma_dnrm2)(blas_int* n, const double* x, blas_int* incx);
                       ^
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:294:56: warning: declaration of ‘void zgemm_(const char*, const char*, const int*, const int*, const int*, const Rcomplex*, const Rcomplex*, const int*, const Rcomplex*, const int*, const Rcomplex*, Rcomplex*, const int*)’ with C language linkage [enabled by default]
       const Rcomplex *beta, Rcomplex *c, const int *ldc);
                                                        ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:44:22: warning: conflicts with previous declaration ‘void arma::zgemm_(const char*, const char*, const blas_int*, const blas_int*, const blas_int*, const void*, const void*, const blas_int*, const void*, const blas_int*, const void*, void*, const blas_int*)’ [enabled by default]
   #define arma_zgemm zgemm
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:102:8: note: in expansion of macro ‘arma_fortran’
   void arma_fortran(arma_zgemm)(const char* transA, const char* transB, const blas_int* m, const blas_int* n, const blas_int* k, const void*   alpha, const void*   A, const blas_int* ldA, const void*   B, const blas_int* ldB, const void*   beta, void*   C, const blas_int
        ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:102:21: note: in expansion of macro ‘arma_zgemm’
   void arma_fortran(arma_zgemm)(const char* transA, const char* transB, const blas_int* m, const blas_int* n, const blas_int* k, const void*   alpha, const void*   A, const blas_int* ldA, const void*   B, const blas_int* ldB, const void*   beta, void*   C, const blas_int
                     ^
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:299:35: warning: declaration of ‘void zgemv_(const char*, const int*, const int*, const Rcomplex*, const Rcomplex*, const int*, const Rcomplex*, const int*, const Rcomplex*, Rcomplex*, const int*)’ with C language linkage [enabled by default]
       Rcomplex *y, const int *incy);
                                   ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:39:22: warning: conflicts with previous declaration ‘void arma::zgemv_(const char*, const blas_int*, const blas_int*, const void*, const void*, const blas_int*, const void*, const blas_int*, const void*, void*, const blas_int*)’ [enabled by default]
   #define arma_zgemv zgemv
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:97:8: note: in expansion of macro ‘arma_fortran’
   void arma_fortran(arma_zgemv)(const char* transA, const blas_int* m, const blas_int* n, const void*   alpha, const void*   A, const blas_int* ldA, const void*   x, const blas_int* incx, const void*   beta, void*   y, const blas_int* incy);
        ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:97:21: note: in expansion of macro ‘arma_zgemv’
   void arma_fortran(arma_zgemv)(const char* transA, const blas_int* m, const blas_int* n, const void*   alpha, const void*   A, const blas_int* ldA, const void*   x, const blas_int* incx, const void*   beta, void*   y, const blas_int* incy);
                     ^
In file included from /usr/include/R/R_ext/Applic.h:41:0,
                 from fitglmm.cpp:50:
/usr/include/R/R_ext/BLAS.h:340:21: warning: declaration of ‘void zherk_(const char*, const char*, const int*, const int*, const double*, const Rcomplex*, const int*, const double*, Rcomplex*, const int*)’ with C language linkage [enabled by default]
       const int *ldc);
                     ^
In file included from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo:54:0,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/RcppArmadillo.h:31,
                 from fitglmm.cpp:47:
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:50:22: warning: conflicts with previous declaration ‘void arma::zherk_(const char*, const char*, const blas_int*, const blas_int*, const double*, const void*, const blas_int*, const double*, void*, const blas_int*)’ [enabled by default]
   #define arma_zherk zherk
                      ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:47:44: note: in definition of macro ‘arma_fortran2_noprefix’
   #define arma_fortran2_noprefix(function) function##_
                                            ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:108:8: note: in expansion of macro ‘arma_fortran’
   void arma_fortran(arma_zherk)(const char* uplo, const char* transA, const blas_int* n, const blas_int* k, const double* alpha, const   void* A, const blas_int* ldA, const double* beta,   void* C, const blas_int* ldC);
        ^
/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include/armadillo_bits/def_blas.hpp:108:21: note: in expansion of macro ‘arma_zherk’
   void arma_fortran(arma_zherk)(const char* uplo, const char* transA, const blas_int* n, const blas_int* k, const double* alpha, const   void* A, const blas_int* ldA, const double* beta,   void* C, const blas_int* ldC);
                     ^
fitglmm.cpp: In function ‘double Loglikelihood2(int, double*, void*)’:
fitglmm.cpp:367:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(i=0; i<q2; ++i) {
             ^
fitglmm.cpp: In function ‘SEXPREC* glmm_score_text(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
fitglmm.cpp:661:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for(size_t i=0; i<infile_header_print.size(); ++i) {
                                                   ^
fitglmm.cpp:713:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            if (infile_ncol_print_idx<infile_ncol_print.size()) {
                                                             ^
fitglmm.cpp:714:67: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                  if(infile_ncol_print[infile_ncol_print_idx] == k+1) {
                                                                   ^
fitglmm.cpp:794:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for(size_t i=0; i<infile_header_print.size(); ++i) {
                                                   ^
fitglmm.cpp:846:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            if (infile_ncol_print_idx<infile_ncol_print.size()) {
                                                             ^
fitglmm.cpp:847:67: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                  if(infile_ncol_print[infile_ncol_print_idx] == k+1) {
                                                                   ^
fitglmm.cpp: In function ‘SEXPREC* glmm_score_bed(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
fitglmm.cpp:999:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(size_t j=0; j<nblocks; ++j) {
                           ^
fitglmm.cpp:1002:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
              if(ncount == ns && j == nblocks - 1) {break;}
                                                ^
fitglmm.cpp: In function ‘SEXPREC* glmm_wald_text(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
fitglmm.cpp:1149:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            if(infile_ncol_print[infile_ncol_print_idx] == k+1) {
                                                             ^
fitglmm.cpp:1221:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
            if(infile_ncol_print[infile_ncol_print_idx] == k+1) {
                                                             ^
fitglmm.cpp: In function ‘SEXPREC* glmm_wald_bed(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
fitglmm.cpp:1325:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(size_t j=0; j<nblocks; ++j) {
                           ^
fitglmm.cpp:1328:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
              if(ncount == ns && j == nblocks - 1) {break;}
                                                ^
fitglmm.cpp:1373:77: warning: ‘nmiss’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return List::create(Named("snpinfo") = infile_header_print, Named("N") = n-nmiss, Named("AF") = gmean, Named("G") = g, Named("skip") = skip);
                                                                             ^
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I"/home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fpic -fPIC   -c registerDynamicSymbol.c -o registerDynamicSymbol.o
g++ -m64 -shared -L/usr/lib64/R/lib -o GMMAT.so fitglmm.o registerDynamicSymbol.o -L/usr/lib64/R/lib -lRlapack -L/usr/lib64/R/lib -lRblas -lgfortran -lm -lboost_iostreams -L/usr/lib64/R/lib -lR
installing to /home/ji3x/R/x86_64-redhat-linux-gnu-library/3.4/GMMAT/libs
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘GMMAT’
    finding HTML links ... done
    GMMAT-package                           html  
    example                                 html  
    glmm.rvtests                            html  
    glmm.rvtests.meta                       html  
    glmm.score                              html  
    glmm.score.meta                         html  
    glmm.wald                               html  
    glmmkin                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (GMMAT)
"

**Comment by hanchenphd** [comment]
Hi Jamie,

I am not sure where the problem came from. Did you successfully install all the dependencies (R and Bioconductor packages)? Did glmmkin and glmm.score functions work?

Best,
Han

**Comment by jinshaw16** [comment]
Dear Han,

One of the problems is that my GRM is not positive semi-definite. I will change that and see if I still get the same behaviour. Thank you for getting back to me, I'll let you know either way.

Best wishes,

Jamie
