### ISSUE TITLE
Progress bar for SMMAT

### ISSUE THREAD

**Issue by PaulTimmers** [hanchenphd/GMMAT#13]
Since SMMAT loops over variant sets, would it be possible to implement a verbose option that reports how many sets it has already analysed (or some kind of progress bar)?

**Comment by hanchenphd** [comment]
Thank you for the suggestion. We are working on optimizing parallel computing for SMMAT and will think about it. It could be challenging to show the progress bar with multi-threading though.

Best,
Han

**Comment by hanchenphd** [comment]
Progress bar implemented in version 1.3.1.
