### ISSUE TITLE
ANOVA between 2 glmkin models

### ISSUE THREAD

**Issue by TeaByrd** [hanchenphd/GMMAT#14]
Hey guys,

I'm wondering if it's possible to do an ANOVA between two glmkin models in this package? Or relatively straight forward with another package that can handle the GMMAT models? 

My two models only differ in the fact that model 2 was built with one additional independent variable. I want to test, if this additional variable has a significant contribution to the model.

Thanks in advance and best,
Thomas

**Comment by hanchenphd** [comment]
Hi Thomas,

No, GMMAT does not report the actual likelihood because the GLMM is fitted using the penalized quasi-likelihood. In your case you can conduct a Wald test on that additional effect parameter, which is asymptotically equivalent to a likelihood ratio test.

Best,
Han
