### ISSUE TITLE
Changelog for 1.3.1?

### ISSUE THREAD

**Issue by agilly** [hanchenphd/GMMAT#16]
Just noticed 1.3.1 was committed about a month ago. Since this was not packaged as a release, is it safe to use?

We are using the previous version of SMMAT and are thinking of upgrading to 1.3.1. Can you provide a changelog? I've noticed there is a memory optimised variant set test now. Are multiallelics supported?

Thanks,

Arthur

**Comment by hanchenphd** [comment]
Hi Arthur,

Yes, the same version is also available on CRAN. For SMMAT there were no major changes (only the two-step low-memory version was implemented). See Section 8.18 of the [user manual](https://github.com/hanchenphd/GMMAT/blob/master/inst/doc/GMMAT.pdf).

For multiallelic variants, if they are coded "T,C,G" in the GDS file, then each copy of both C and G would be treated as 1; if they are coded as two variants "T,C" and "T,G" with the same position in the GDS file, then they would be treated as two different variants with T,G as 0 and C as 1 for the first variant, and T,C as 0 and G as 1 for the second variant, respectively. I have seen both types of GDS files, so users have the flexibility of deciding how they would like to treat multiallelic variants, and they can create their GDS files accordingly.

Thanks,
Han
