### ISSUE TITLE
glmmkin is slow with a large sample size

### ISSUE THREAD

**Issue by ianyang819** [hanchenphd/GMMAT#21]
Dear Dr. Chen,

I have just started using SMMAT and it seems that glmmkin is kind of slow when fitting the null model particularly when the sample size is large. For example, when n=7000, it took about 50 minutes to complete fitting the null model using glmmkin(disease ~ sex, data = pheno, kins = GRM, id = "id", family = binomial(link = "logit")) with GRM being a 7000x7000 matrix. I am wondering if there are any options that can make the function faster or if I am using the function correctly. The function is fast when the sample size is small, say, n=1000.

Updated 03/29/2021: used glmmkin(disease ~ sex, data = pheno, kins = NULL, id = "id", family = binomial(link = "logit")), got the same p-values, and the function was no longer slow. Would you happen to know the reason? Thanks!

Sincerely,

Ian

**Comment by hanchenphd** [comment]
Hi Ian,

Thank you for your interest in GMMAT. The speed depends on the R version and the specific machine that you use. If you have an Intel CPU, you can dramatically speed up by using an R version compiled with Intel MKL. Please see Section 3.2 of the [user manual](https://github.com/hanchenphd/GMMAT/blob/master/inst/doc/GMMAT.pdf) for details.

Best,
Han

**Comment by ianyang819** [comment]
Thanks a lot for your prompt response, Dr. Chen. I have used glmmkin(disease ~ sex, data = pheno, **kins = NULL**, id = "id", family = binomial(link = "logit")), got the same p-values, and the function was much faster. I am wondering - under what circumstances would kins=GRM and kins=NULL produce different p-values? If they produce the same results most of the time, I'd prefer to use kins=NULL for my analysis because it is much faster.

**Comment by hanchenphd** [comment]
Hi Ian,

The argument `kins = NULL` means that you want to run a regular logistic regression (without any random effects). It is faster but does not typically give you the same results as compared to a logistic mixed model. However, sometimes your variance component estimate with `kins` would converge to 0, then a logistic mixed model would be equivalent to a regular logistic regression. You can pull out the `theta` component from your fitted null logistic mixed model object to verify that.

Best,
Han
