### ISSUE TITLE
Variance estimate on the boundary of the parameter space observed, refitting model... 

### ISSUE THREAD

**Issue by ryshi06** [hanchenphd/GMMAT#23]
Dear Dr. Chen, 

I recently started to perform linear mixed effect model for longitudinal dependent variables (repeated measures for each sample and the specific dependent variable I use is the interval data for each sample, i.e., if a person has 3 measurements in total, he has two interval data as dependent variable) using GMMAT glmmkin function with family = gaussian(link = "identity"). However, when performing the random intercept model, I got a warning of "Variance estimate on the boundary of the parameter space observed, refitting model... ". I have searched on google and cannot figure out why the glmmkin gives me warning like this. Also, I am curiously about the "refitting model" issue. What does this mean and what model does this command fit.

Best regards,
Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

Thank you for your interest in GMMAT! This warning message usually means one of your variance component parameter estimate was converged to 0. Sometimes it can cause other variance component estimates to be numerically inaccurate. When this happens, glmmkin would refit the model again by forcing this particular variance component parameter to be fixed at 0, and only update the other variance component estimates.

You can turn on `verbose = TRUE` to see which variance component parameter estimate was converged to 0.

Best,
Han

**Comment by ryshi06** [comment]
Hi Dr. Chen,

Thanks for the really quick reply! I added "verbose=TRUE", but I am sorry that I cannot understand the results very clearly. From my results, I have Iteration from 1 to 12 and then Iteration 1 to 3. In the process of iteration 1 to 12, my Variance component estimates started to become 0.0000 at iteration 8, and all the Fixed-effect coefficients mainly remain the same. I am curious about does this 0 variance component variance means the generalized linear mixed effect model is not appropriate for my data or not?

Best regards,
Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

How many variance components (including the residual variance) did you have? Which one converged to 0?

Best,
Han

**Comment by ryshi06** [comment]
Hi Dr. Chen,

My model is simply like this: model <- glmmkin(delta_y/delta_t ~ x1 + x2 + x3, data = data, id = id, family = gaussian(link = "identity"), verbose = TRUE), so I think I only have the identity matrix. And the kins value equals to 0 in the theta.

Best regards,
Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

In your case, the random intercept for repeated measures was 0 and your model was reduced to a linear regression model with no repeated measurement effects. That's what you get from your data.

Best,
Han

**Comment by ryshi06** [comment]
Hi Dr. Chen,

Thanks so much for your clarification. This is what I thought after I noticed the variance estimate is 0. I need to think more.

Thanks again!

Best regards,
Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

You are welcome. Thank you for your interest in GMMAT!

Best,
Han
