### ISSUE TITLE
How can I calculate Odds ratio or Z-score from the outcome of glmm.score?

### ISSUE THREAD

**Issue by ConnieXuhm** [hanchenphd/GMMAT#24]

**Comment by hanchenphd** [comment]
You cannot calculate an odds ratio from a score test. Under the assumption of small genetic effects, you may be able to approximate the odds ratio by exp(SCORE/VAR). The z-score is SCORE/sqrt(VAR).

Best,
Han

**Comment by ConnieXuhm** [comment]
Thanks @hanchenphd ! I will try it!
