### ISSUE TITLE
Calculate effect size for minor allele (A1) in the glmm.wald() test

### ISSUE THREAD

**Issue by ryshi06** [hanchenphd/GMMAT#26]
Hi,

I found there is an option for the variant set tests SMMAT called "use.minor.allele" to use the minor allele as coding allele, but I did not find a similar function for the single variant tests glmm.wald(). The effect size generated from glmm.wald() is for A2, is there any possible way to switch it to A1? If not, I am wondering whether the effect size estimated for A2 is the negative value of effect size estimated for A1? 

Sorry for bothering.

Best,
Shi

**Comment by hanchenphd** [comment]
Yes, the effect size estimate for A1 is the negative value of the effect size estimate for A2.

**Comment by ryshi06** [comment]
Thanks!
