### ISSUE TITLE
How could I get the group definition file? 

### ISSUE THREAD

**Issue by lpalvin** [hanchenphd/GMMAT#29]
How could I get the group definition file? I want to use SMMAT to analyze rare mutations, but I don't know how to get the group file.

**Comment by hanchenphd** [comment]
This file should be created by yourself. Please see Section 5.3.1 of the [user manual](https://github.com/hanchenphd/GMMAT/blob/master/inst/doc/GMMAT.pdf) for an example.

**Comment by lpalvin** [comment]
> This file should be created by yourself. Please see Section 5.3.1 of the [user manual](https://github.com/hanchenphd/GMMAT/blob/master/inst/doc/GMMAT.pdf) for an example.

I can’t understand how this file was created directly by looking at the example. Is it to classify snp annotated to the same gene? Very thanks！

**Comment by lpalvin** [comment]
> "A group definition file with no header and 6 columns (variant set id, variant chromosome, variant position, variant reference allele, variant alternate allele, weight) is also required."
> You will need this file to tell the function which variants should be grouped together in the test. For example, if you want to group your variants based on their gene annotations, then the first column could be the gene name or Ensembl gene ID. If you want to group your variants based on physical positions (e.g., in a sliding window analysis), then the first column could be the name of the test regions (e.g., chr1:10001_14000). Variants with the same variant set id (the first column) are tested together.

Thank you！This helped me a lot!
