### ISSUE TITLE
SMMAT read error

### ISSUE THREAD

**Issue by angelcymak** [hanchenphd/GMMAT#3]
Hi,

I just noticed an issue within the SMMAT function. The issue occurs on this line:
 group.info <- try(read.table(group.file, header = FALSE, stringsAsFactors = FALSE, sep = group.file.sep), silent = TRUE)

It would read in the T allele as boolean instead of characters. Including colClass seems to fix the issue:
colClasses = c("character","character","character","character","character","numeric")

**Comment by hanchenphd** [comment]
Thanks for catching this issue! We will make improvements in the next released version. It happens only when all of your reference or alternate alleles are T, which is a rare case in practice.
