### ISSUE TITLE
glmm.wald. SNP names in when infile is gds

### ISSUE THREAD

**Issue by gustavahlberg** [hanchenphd/GMMAT#33]
Hi,
For the option "snps" in the function glmm.wald: What are the snp names in a gds file?
I have tried to give the variant.ids that I want it to run. But everything just comes back as NA.

**Comment by hanchenphd** [comment]
It's the variant name on the "annotation/id" note. For example, if you open your gds file you should be able to retrieve these names from `SeqArray::seqGetData(gds, "annotation/id")`.

**Comment by gustavahlberg** [comment]
Found it. Great! Thanks!
