### ISSUE TITLE
burden effect size in SMMAT

### ISSUE THREAD

**Issue by agilly** [hanchenphd/GMMAT#35]
SMMAT returns `B.score` and `B.var`. Since a burden collapses individual genotypes into a single virtual genotype, it should be possible to obtain a `beta` and `se`. Is there a way to calculate these from the score and variance?

**Comment by hanchenphd** [comment]
Yes! The effect size beta can be calculated as B.score/B.var, and the SE of beta can be calculated as 1/sqrt(B.var).

Best,
Han
