### ISSUE TITLE
Meta-analysis for single score test error

### ISSUE THREAD

**Issue by ryshi06** [hanchenphd/GMMAT#37]
Hi, 

I was trying to perform a meta-analysis on three single score test outputs, but I receive an error of "Error in glmm.score.meta(files = c(glmm1.ann.raw.score0.int, glmm2.ann.raw.score0.int,  : 
  Error: "SNP" must have the same length as "files"!"

Basically, I am not sure what this error message means, but I checked the unique length of SNPs in each study, and the results were listed here. 

> length(unique(glmm2.ann.raw.score0.int$SNP))
[1] 800076
> length(unique(glmm1.ann.raw.score0.int$SNP))
[1] 9195781
> length(unique(glmm3.ann.raw.score0.int$SNP))
[1] 8442141

Thanks so much for helping!

Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

Thank you for your interest in GMMAT. The first argument `files` needs to be a character vector of the file names, and the `SNP` argument needs to be a character vector of the same length as `files`. See the [help document](https://github.com/hanchenphd/GMMAT/blob/master/man/glmm.score.meta.Rd).

Best,
Han
