### ISSUE TITLE
Error in Single Variant Wald Test

### ISSUE THREAD

**Issue by ryshi06** [hanchenphd/GMMAT#38]
Hi Han,

Sorry for bothering again, I have met an error of Error in glmm.wald(fixed = dmmse_int ~ MMSE_init + age_init_visit + sex +  : 
  Expecting a single string value: [type=integer; extent=1]. 

The score test works well.

Can you point out what is happening here? Very appreciated!

Best,
Ruyu

**Comment by hanchenphd** [comment]
Hi Ruyu,

It would be most helpful if you can send me a reproducible example, and I will take a look.

Thanks,
Han

**Comment by ryshi06** [comment]
Hi Han,

I am not sure what part causes the problem, and I think the data I have is secure, so I am not sure how to create a reproducible example... Sorry for that. Do you have any other suggestions or ideas? 

Ruyu

**Comment by hanchenphd** [comment]
You can send me a simulated example that shows the problem.

Best,
Han

**Comment by ryshi06** [comment]
I actually have no idea how to create a simulated example showing the same error...

**Comment by hanchenphd** [comment]
Can you show your code? I may be able to see the problem if it was a simple syntax error. Otherwise you can replace your sample ID's and data by fake numbers and send them to me.

Best,
Han

**Comment by ryshi06** [comment]
Can you leave an email? I'll send you through email. Thanks!

Ruyu

**Comment by hanchenphd** [comment]
Please see [the GMMAT homepage](https://github.com/hanchenphd/GMMAT#contact).
