### ISSUE TITLE
Using dosages from text file or VCF

### ISSUE THREAD

**Issue by dylkot** [hanchenphd/GMMAT#39]
Hi there, thanks for this great tool! I am trying to use dosage information in my analysis. If I create a text file of the dosages, it seems I can't use parallelization (getting an error message saying parallelization isn't implemented for text files). Further, I am getting segfaults when I run the analysis:

```
glmm.score(model0, infile = genotypefn, outfile=outfn, ncores=1)
```

gives 

```

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: glmm.score(model0, infile = genotypefn, outfile = outfn, ncores = ncores)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault (core dumped)
```

This is for 100 variants X 2000 samples. Alternatively if I try to use a VCF file like so:

```
SeqArray::seqVCF2GDS(vcffn, gdsfn, parallel=TRUE, fmt.import="DS")
glmm.score(model0, infile = gdsfn, outfile=outfn, ncores=7)
```

it completes but doesn't seem to be using the dosage information. Any idea if it is possible to use the dosage information from the VCF file and if there is an obvious problem with the text file? Or any other work arounds to use dosage information, ideally with parallelization?

Thanks!

**Comment by dylkot** [comment]
I think that fixes it for the VCF file approach. It runs smoothly and returns results that are subtly different from the hard thresholded results. The text file approach just runs really slowly and hasn't returned anything after an hour or two which doesn't really make sense since it is only about 150 variants. The first few columns/lines of the file are like this:

```
1:723918[b37]G,A        G       A       2.0     2.0     2       1.0     1       2.0     2.0     2       2.0     2.0     2.0     2.0     2.0     2.0     1.0     2       2.0
1:724169[b37]A,G        A       G       2.0     2.0     2       2.0     2       2.0     2.0     2       2.0     2.0     2.0     2.0     2.0     2.0     2.0     2       2.0
1:725286[b37]G,A        G       A       1.0     2.0     2       2.0     2       2.0     2.0     2       2.0     2.0     2.0     2.0     2.0     2.0     2.0     2       1.0
1:729940[b37]C,G        C       G       1.0     2.0     1       2.0     2       2.0     2.0     1       1.0     2.0     2.0     2.0     2.0     2.0     1.0     2       1.15
1:730232[b37]C,T        C       T       2.0     2.0     2       2.0     2       2.0     2.0     2       1.0     2.0     2.0     2.0     2.0     2.0     1.0     2       2.0
```

Does that seem right to you? 

Apologies for an unrelated add-on question, but it isn't really a github issue worth opening an issue for. But do you still recommend using principle components to correct for population stratification like you did in the paper GMMAT? I've seen a few other mixed linear models analyses where they don't include PCs assuming that that should be captured in the random effects, as long as you use the full set of variants to calculate the relatedness matrix rather than just a pruned subset. 

Thanks so much!

**Comment by hanchenphd** [comment]
> 

You might need to skip the first three columns using `infile.ncol.skip = 3`. See `?glmm.score` for details.

Regarding your second question, see [Tucker, Price and Berger 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4096359/). If there is strong confounding by population structure, I would always include top PCs as fixed-effects covariates (it probably does not matter if confounding is weak).

Best,
Han

**Comment by dylkot** [comment]
Got it, thank you!! Apologies, that wasn't very clear form section 4.3 [here](https://cran.r-project.org/web/packages/GMMAT/vignettes/GMMAT.pdf) but I see it clearly in ```?glmm.score```

**Comment by hanchenphd** [comment]
> Got it, thank you!! Apologies, that wasn't very clear form section 4.3 [here](https://cran.r-project.org/web/packages/GMMAT/vignettes/GMMAT.pdf) but I see it clearly in `?glmm.score`

Also see an example of using `glmm.score` with a plain text genotype file in Section 5.2.1 of the [user manual](https://github.com/hanchenphd/GMMAT/blob/master/inst/doc/GMMAT.pdf).

Best,
Han

**Comment by dylkot** [comment]
Thank you, yes I totally missed that! 

Best,
Dylan
