### ISSUE TITLE
infinite or missing values in 'x'

### ISSUE THREAD

**Issue by agilly** [hanchenphd/GMMAT#4]
Hi,

I am trying to run SMMAT. Fitting the null model works without problems, but when I run :

```R
SMMAT(null.obj = model0,
        geno.file = GDFList,
        group.file = group_file,
        MAF.range=c(1e-10, 0.05),
        MAF.weights.beta = c(1,1),
        miss.cutoff=0.01,
        tests=c("O", "E"),
        rho=(0:10)/10,
        use.minor.allele=T,
        Garbage.Collection = T,
        ncores=nthread,
        meta.file.prefix = outfile)
```

I get the following:

```
Error in { : task 2 failed - "infinite or missing values in 'x'"
Calls: run_SMMAT -> SMMAT -> %dopar% -> <Anonymous>
```

It only happens for some particular chunks of the data, so I assume it is a particular combination of genotype and phenotype causing this. Have you encountered this error before?

Thanks,

Arthur

**Comment by agilly** [comment]
Also tried filtering out monomorphics like this, no change:

```R
seqSetFilter(f, sample.id=pheno$id)
frq=seqAlleleFreq(f, .progress=T)
variant.id <- seqGetData(f, "variant.id")
seqSetFilter(f, variant.id=variant.id[frq>0 & frq<1])
seqExport(f, "test.gds")
```

**Comment by hanchenphd** [comment]
I will look into this. Could you please send a minimum reproducible example to Han.Chen.2@uth.tmc.edu?

Thanks,
Han

**Comment by agilly** [comment]
Working on it, I need to anonymise and shuffle everything. In the meantime I've managed to get a more precise error message by running single-threaded:

```
Error in eigen(V.temp, only.values = TRUE, symmetric = TRUE) :
  infinite or missing values in 'x'
Calls: run_SMMAT -> SMMAT -> .skato_pval -> eigen
Execution halted
```

**Comment by agilly** [comment]
Strange. I can't seem to reproduce the error on a single variant set. I added `print(groups[i]);print(groups[i+1])` at line 267 in `SMMAT.R`. When I use my genome-wide list of variant sets, it crashes with the above error. When I take the variant sets corresponding to `i` and `i+1`, I would expect the crash to happen, but it doesn't. Will look into it more.
