### ISSUE TITLE
ERROR glmm.wald()

### ISSUE THREAD

**Issue by MARCPUCV** [hanchenphd/GMMAT#49]
Hi,
I have a query I am running the wald test and I get the following error (Error in if (!id %in% names(data)) stop("Error: "id" must be one of the variables in the names of "data".") : the condition has length > 1) I am using the sample script from the GMMAT package. I don't know why it is giving this error could you help me. Thank you very much. Cheers!!

**Comment by hanchenphd** [comment]
Can you share your command and R version number? I will see if I can reproduce the error message.

Thanks,
Han

**Comment by MARCPUCV** [comment]
Hello,
Thank you very much for your prompt response. I already managed to run the wald test.
