### ISSUE TITLE
Class probabilities in output

### ISSUE THREAD

**Issue by LiliiaY** [hanchenphd/GMMAT#55]
Hello,
Thank you for such a great package!
Can you please advise me how I can modify the project code to get predicted probabilities or class labels after using the glmm.score function? I'd like to estimate the model performance.

Best regards,
Liliia

**Comment by hanchenphd** [comment]
Hi Liliia,

Thank you for your interest in GMMAT. The function `glmm.score` performs score tests and it does not provide any predicted probabilities. You might want to check out the model fitting function `glmmkin` instead. One component in the returned list is `fitted.values`, and maybe that is what you need.

Thanks,
Han
