### ISSUE TITLE
Inflation observed for O.minp

### ISSUE THREAD

**Issue by agilly** [hanchenphd/GMMAT#6]
Hi Han,

just a question w.r.t. the interpretation of results. I am running many parallel RVAS, and measuring the genomic inflation factor lambda as a quality check. While `E.pval` and `O.pval` are relatively well-controlled, I observe a very strong inflation for `O.minp`. When I calculate lambdas for p-values produced by MONSTER (also a GMM with O-test and rho-optimisation) I get no inflation.

Could you tell me which p-value I should use for the O-test? The documentation says that `O.minp` is the minimum p-value observed along the rho search grid. Is `O.pval` that p-value but corrected for the number of rhos tested?

Thanks,

Arthur

**Comment by hanchenphd** [comment]
Yes, O.minp is the minimum p-value observed from the search grid, and it does not follow a uniform distribution under the null hypothesis. O.pval is the p-value corrected for the search grid by numerical integration.

**Comment by agilly** [comment]
Great, thanks for the clarification!
