### ISSUE TITLE
Issue when adjusting for many covariates

### ISSUE THREAD

**Issue by e-jorsboe** [hanchenphd/GMMAT#7]
Hi there,

I am trying to run GMMAT logistic mixed model using the wald test (more specifically glmm.wald()). And it has worked fine up until now. First I did association adjusting for age and gender as covariates. However I now want to also adjust for cohort, meaning including it as covariates. However I cannot fit the model and I get the following error (I have tried both the logistic and linear mixed model - this error is from fitting a linear model):

[1] "this many being analysed:"
Error in chol.default(crossprod(X, Sigma_iX)) :
  the leading minor of order 6 is not positive definite

My design matrix looks something like this:

geno gender age cohort1 cohort2
 0   1  57   1        0
 0   2  59   1        0
 0   2  59   1        0
 0   2  62   1        0
 0   2  64   1        0
 0   2  55   1        0

The cohort1 and cohort2 columns are dummy variables and only have 0 and 1's values. They often both have the value of 0. But not both 1. If I run the model with just age and gender it works fine. I have tried doing the same model in GEMMA and that worked. 

So what is causing this issue? And is there a workaround?

**Comment by hanchenphd** [comment]
I believe it was caused by collinearity in your model.matrix. A simple way to troubleshoot this issue is to run a linear regression lm( ) for any outcome (could even be simulated) on these variables and see if any coefficients are NA. If that is the case you can drop those variables.

**Comment by e-jorsboe** [comment]
Hi,

I think I solved the problem. However for your notice, it seems that the wald.test has a hard time converging (it just runs forever and then gives some error) if one of the columns is very sparse. That is if it only has a few 1's and mostly 0's. Like for instance if one is adjusting for a cohort very few individuals, in an otherwise big data set.
