### ISSUE TITLE
glmmkin is incompatible with tibbles

### ISSUE THREAD

**Issue by weinstockj** [hanchenphd/GMMAT#8]
Hi GMMAT developers,

If supplying a `tibble` object as the data argument to glmmkin, the function will fail due to different indexing semantics between `tibbles` and `data.frames`. Please see the following line:

https://github.com/hanchenphd/GMMAT/blob/d18cc6bd08fb67546e0fd4ea66e40625c4d002a0/R/glmmkin.R#L63

Indexing a `tibble` in this manner will return a `tibble` as the result, which won't work with `match`.
With a dataframe, this will work, as it will return a vector. Might I suggest either an input validation to ensure the data argument is **not** a `tibble`, or use the following indexing scheme to ensure vector output:

`data[idx, ][[id]]`

Thanks for developing GMMAT,
Josh

**Comment by hanchenphd** [comment]
Hi Josh,

Thank you for this bug report! I have implemented a temporary fix that explicitly converts tibble objects to data.frame objects. I will look into your suggestion and include a permanent solution in the next version when I get a chance to test the code extensively.

Best,
Han

**Comment by weinstockj** [comment]
Great, thanks!
