### ISSUE TITLE
P-value from glmmkin

### ISSUE THREAD

**Issue by dheerajbobbili1988** [hanchenphd/GMMAT#9]
Hi,

Thank you for this very useful package. I am new to this kind of analysis and  I am trying to fit a glm for a polygenic risk score analysis using family data. I managed to calculate the GRM using GMMAT package and tried to fit the model. Everything works however, I have two questions:

1. I am used to the standard glms, where we can look at the P-value and generate odds ratios from the glm models. Is there a way to extract this information from the models generated via glmmkin function?
2. In PRS research it is standard to extract the variance explained (R2) in order to measure the heritability. Is it also possible to do it by gmmat package?

I just pasted my formula just for your reference

``model_aff = glmmkin(AFF ~ PRS+SEX, data = infile, kins = K, id = "IID", family = binomial(link = "logit"))``

Thanks,

**Comment by hanchenphd** [comment]
Thank you for your interest in GMMAT! Please see my comments below.

Best,
Han

> Hi,
> 
> Thank you for this very useful package. I am new to this kind of analysis and I am trying to fit a glm for a polygenic risk score analysis using family data. I managed to calculate the GRM using GMMAT package and tried to fit the model. Everything works however, I have two questions:
> 
> 1. I am used to the standard glms, where we can look at the P-value and generate odds ratios from the glm models. Is there a way to extract this information from the models generated via glmmkin function?
>>> You can construct a Wald test by yourself to compute the p-values for the fixed-effects estimates. The effect estimates are model_aff$coefficients, and the variances (NOT SE's, but the square of SE's) are diag(model_aff$cov). The odds ratios are exp(model_aff$coefficients).

> 2. In PRS research it is standard to extract the variance explained (R2) in order to measure the heritability. Is it also possible to do it by gmmat package?
>>> No. Not for binary traits.

> 
> I just pasted my formula just for your reference
> 
> `model_aff = glmmkin(AFF ~ PRS+SEX, data = infile, kins = K, id = "IID", family = binomial(link = "logit"))`
> 
> Thanks,

**Comment by dheerajbobbili1988** [comment]
Thank you for your help!!

**Comment by TeaByrd** [comment]
> Hi @TeaByrd ,
> 
> Yes, I used the same strategy as @hanchenphd suggested, the only difference is I used the wald test function:
> 
> `library(aod)`
> `wald.test(mod$cov, mod$coefficients, Terms = 2:6)`
> 
> Hope it helps

Nice, I'm using it too.  If I put it: Terms = 1:6, it includes the intercept ?

**Comment by dheerajbobbili1988** [comment]
@TeaByrd Yes, I think so.
